// TIMING IN COMBINATIONAL TESTBENCH
// GENERATOR CLASS SHOULD GENERATE INPUTS WITH SOME DELAY
// DRIVER AND MONITOR SHOULD HAVE SAME TIMING  - I USED #0 DELAY IN THEM
// SCOREBOARD AND TRANSACTION CLASSES NEED NO DELAY
// WHAT IS #0 DELAY?
// #0 MEANS ?wait for the current work to finish, then continously
// BY INCLUDING #0, simulator says:
// I have changed the inputs. Let every combinational logic update first. Then I will read the outputs.?
// PACKAGE FILE INCLUDES ALL THE CLASSES AND THEIR DEFINITIONS
// WHY WE USED TASKS AND WHY NOT FUNCTIONS?
// FUNCTION EXECUTES IN 0 TIME, WHILE TASKS CONSUMES TIME
// ALSO FUNCTIONS CAN NOT CONTAIN USE #, @, wait, forever KEYWORDS
// MAILBOX OPERATIONS - put() AND get() ARE TASKS, SO THEY CAN'T BE USED WITHIN FUNCTIONS.
package adder_classes;

// global parameter
parameter GLOBAL_N = 4;

//create first class for transaction
// pass parameter size in all classes
class trans #(parameter N = GLOBAL_N);
	rand bit [N-1:0] a; 
	rand bit [N-1:0] b;
	// they can't be given rand data type because outputs
	// will be generated by the DUT
	bit [N-1:0] s;
	bit cout;

	// display function for debugging
	//function void display(string tag);
        //	$display("%s, Time = %0t, a = %0d, b = %0d",tag,$time,a,b);
	// endfunction
endclass

//create second class which is generator
// pass parameter size in all classes
class generator #(parameter N = GLOBAL_N);
	trans #(N) T;
	mailbox #(trans #(N)) gen2drv; //mailbox that send data to generator class
	// gen2drv is mailbox handle
	// we can't simply write gen2drv = new(); just like T = new(); 
	// because mailbox is a shared entity between generator and driver class
	//custom constructor for mailbox
	function new(mailbox #(trans #(N)) gen2drv_arg);
		// if class handle (gen2drv) and function's argument (gen2drv_arg)
		// are different, we don;t write "this" keyword
		gen2drv = gen2drv_arg; //unbounded memory allocated for gen2drv object
		// only generator class will create a mailbox, rest will be connected to this
		// because overall there is only one shared mailbox accross the environment
		// we can also declare a shared mailbox in tb_top and use it here in all classes
	endfunction
	// Task to generate input stimulus
	task main(int no_of_inputs);
		repeat(no_of_inputs) begin
			// Created insisde the loop so that we'll be making 
			// separate transaction object for each input
			//#10;
			T = new(); 
			T.a = $urandom_range((2**N)-1,0);
			T.b = $urandom_range((2**N)-1,0);
			gen2drv.put(T);
		end
	endtask
	// display function for debugging
	//function void display(string tag);
	//	$display("%s, Time = %0t, a = %0d, b = %0d",tag,$time,T.a,T.b);
	//endfunction
endclass

// Driver class
class driver #(parameter N = GLOBAL_N);

	// create virtual interface for driver
	// local handle of interface/dynamic pointer to the physical wires
	virtual add_interface #(.N(N)).driver vif; 
	// .N(N) - Static binding
	// if we write #(N) - Position binding 
	// .N is the parameter name INSIDE the interface file.
	// (N) is the parameter name INSIDE Driver class.
	
	// created a local mailbox handle - this is not a new mailbox
	// This is just an empty pointer for now
	mailbox #(trans #(N)) gen2drv; //shared mailbox of driver and generator
	
	// custom constructor function
	function new(mailbox #(trans #(N)) gen2drv_arg, virtual add_interface #(.N(N)).driver vif); 
	//These function arguments are actual mailbox and interface

		gen2drv = gen2drv_arg; // This connects the driver's local handle to the actual mailbox object
		this.vif = vif; // This connects the driver's local handle to the actual interface
	endfunction
	
	task main();
		forever begin
			// Declaring an empty handle named T of trans 
      			// remember: Do NOT use new() here! The object is already created by the Generator
			trans #(N) T;
			// Block and wait until a packet is available in the mailbox.
      			// Once found, retrieve its memory location and assign it to our handle 'T'.
			gen2drv.get(T);
			vif.a = T.a;
			vif.b = T.b;
			#10;
		end
	endtask
	// display function for debugging
	//function void display(string tag);
	//	$display("%s, Time = %0t, a = %0d, b = %0d",tag,$time,vif.a,vif.b);
	//endfunction
endclass

// Monitor class takes all signals as inputs from DUT thorugh modport and 
// send to scoreboard via mailbox
class monitor #(parameter N = GLOBAL_N);
	// declare vif handle
	virtual add_interface #(N).monitor vif;
	mailbox #(trans #(N)) mon2scb;

	function new (virtual add_interface #(N).monitor vif, mailbox #(trans #(N)) mon2scb);
		this.mon2scb = mon2scb;
		this.vif = vif;
	endfunction

	task main();
		trans #(N) T;
		forever begin
		// check vif.a or vif.b, if any of them changes then only update the value
			//@(vif.a or vif.b);
			#1;
			T = new();

			T.a = vif.a;
			T.b = vif.b;
			T.s = vif.s;
			T.cout = vif.cout;
			
			mon2scb.put(T);
			#9;
			//T.display("MONITOR");
		end
	endtask
	
endclass 

class scoreboard #(parameter N = GLOBAL_N);
	bit [N-1:0] exp_s;
	bit exp_cout;
	int pass_count = 0;
	int fail_count = 0;
	mailbox #(trans #(N)) mon2scb;
	function new(mailbox #(trans #(N)) mon2scb);
		this.mon2scb = mon2scb;
	endfunction
	task main();
		forever begin
			trans #(N) T;
			mon2scb.get(T);
			//#10;
			{exp_cout, exp_s} = T.a + T.b;
			$display("SCOREBOARD: S_dut = %0d, Cout_dut = %d, S_exp = %0d, Cout_exp = %0d", T.s, T.cout, exp_s, exp_cout);
			if( exp_s == T.s && exp_cout == T.cout) pass_count = pass_count + 1;
			else fail_count = fail_count + 1;
		end
	endtask
	function void display();
		if(fail_count > 0)
			$display("Simulation Failed - %0d Test cases failed", fail_count);
		else 
			$display("Simulation Successfull - %0d Test cases Failed and %0d Test cases passed", fail_count, pass_count);
	endfunction

endclass

endpackage
